#!/usr/bin/env python3
"""Build docs/visual-gallery.md from results/figure_manifest.csv."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="results/figure_manifest.csv")
    parser.add_argument("--output", default="docs/visual-gallery.md")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest_path = Path(args.manifest)
    output_path = Path(args.output)

    rows = []
    with manifest_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows.extend(reader)

    lines = []
    lines.append("# Visual Gallery\n")
    lines.append(
        "This page shows all relevant figures extracted from executed outputs in `notebooks/road_collisions_classification.ipynb`.\n"
    )
    lines.append(
        "The images are generated by `scripts/extract_notebook_images.py` and linked here automatically.\n"
    )

    for row in rows:
        image_id = int(row["image_id"])
        title = row["description"]
        rel_path = row["relative_path"]
        # docs/* -> repo root requires ../ prefix
        markdown_path = f"../{rel_path}"

        lines.append(f"## Figure {image_id:02d}: {title}\n")
        lines.append(f"![{title}]({markdown_path})\n")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output_path} with {len(rows)} images")


if __name__ == "__main__":
    main()
